version: '3'
services:
  frontend:
    build:
      context: ./frontend-main
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on: weather-forecasta-api
  weather-forecasta-api:
    build:
      context: ./weather-forecast-api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on: ai-forecast-service
  ai-forecast-service:
    build:
      context: ./ai-forecast-service
      dockerfile: Dockerfile
    ports:
      - '8000:8000'